server:
  port: 80
  context-path: /bos
# 数据源配置
spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/bos
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*/*.xml
logging:
  level: debug