server:
  port: 80
  context-path: /bos
# \u6570\u636E\u6E90\u914D\u7F6E
spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/bos
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
logging:
  level: debug
